### ISSUE TITLE
Bug: Layout shift

### ISSUE THREAD

**Issue by Majorfi** [yearn/b2b-dashboard#147]
### What happened 🆘
When clicking the items in the menu (Overview - yvWFTM - etc.) the switch from regular font to bold font create a layout shift which is unpleasant. This is fixable using some custom CSS pattern

```css
.hover-fix::before {
	display: block;
	content: attr(title);
	font-weight: bold;
	height: 0;
	overflow: hidden;
	visibility: hidden;
}
```

```js
<p
   title={'Something'}
   className={'hover-fix tab'}>
   {'Something'}
</p>
```

### To Reproduce 🔂
Steps to reproduce the behavior: just click another tab

### More 🔎
- Browser : All

## Screenshots

https://user-images.githubusercontent.com/90963895/225890230-ecf96000-31a6-4c27-920f-65f7c10f4ea8.mov
